name: Production Workflow

on:
  release:
    types: [published]

jobs:

  build:
    name: Build production JS
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:

    - name: Check Out
      uses: actions/checkout@v2
    
    - name: Install Node
      uses: actions/setup-node@v2
    
    - name: Install dependencies
      run: npm i
    
    - name: Build
      run: npm run build
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/nominatim.js 
          dist/nominatim.js.map
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
