name: Production Workflow

on:
  release:
    types: [published]

jobs:

  build:
    name: Build production JS
    if: "!github.event.release.prerelease"
    runs-on: ubuntu@latest
    steps:

    - name: Check Out
      uses: actions/checkout@v2
    
    - name: Install Node
      uses: actions/setup-node@v2
    
    - name: Install dependencies
      run: npm i
    
    - name: Build
      run: npm run build
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
          name: nominatim-${GITHUB_REF}
          path: dist/*
